spring.application.name: greenlight-prototype-core-api
spring.profiles.active: local

server:
  port: 18080
  error:
    include-message: always

management:
  server:
    port: 18090
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "info, health, prometheus"
#        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoint:
    info:
      access: unrestricted
    health:
      access: unrestricted
    prometheus:
      access: read_only

logging:
  config: classpath:logback/logback-spring.xml
  loki:
    url: ${LOKI_URL}
#  pattern:
#    level: %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
#  include-application-name: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  
spring:
  data:
    redis:
      cluster:
        max-redirects: 3

redis:
  key-prefix: ${REDIS_KEY_PREFIX}

---
spring.config.activate.on-profile: local
spring:
  data:
    redis:
      cluster:
        nodes:
          - ${REDIS_CLUSTER_MASTER_NODE_1}
          - ${REDIS_CLUSTER_MASTER_NODE_2}
          - ${REDIS_CLUSTER_MASTER_NODE_3}
          - ${REDIS_CLUSTER_WORKER_NODE_1}
          - ${REDIS_CLUSTER_WORKER_NODE_2}
          - ${REDIS_CLUSTER_WORKER_NODE_3}
      password: ${REDIS_PASSWORD}

---
spring.config.activate.on-profile: dev
spring:
  data:
    redis:
      cluster:
        nodes:
          - ${REDIS_CLUSTER_MASTER_NODE_1}
          - ${REDIS_CLUSTER_MASTER_NODE_2}
          - ${REDIS_CLUSTER_MASTER_NODE_3}
          - ${REDIS_CLUSTER_WORKER_NODE_1}
          - ${REDIS_CLUSTER_WORKER_NODE_2}
          - ${REDIS_CLUSTER_WORKER_NODE_3}
      password: ${REDIS_PASSWORD}

---
spring.config.activate.on-profile: live
spring:
  data:
    redis:
      cluster:
        nodes:
          - ${REDIS_CLUSTER_MASTER_NODE_1}
          - ${REDIS_CLUSTER_MASTER_NODE_2}
          - ${REDIS_CLUSTER_MASTER_NODE_3}
          - ${REDIS_CLUSTER_WORKER_NODE_1}
          - ${REDIS_CLUSTER_WORKER_NODE_2}
          - ${REDIS_CLUSTER_WORKER_NODE_3}
      password: ${REDIS_PASSWORD}
management:
  endpoints:
    web:
      base-path: ${GREENLIGHT_ACTUATOR_PATH}