spring.application.name: greenlight-core-api
spring.profiles.active: local

server:
  port: 18080
  url: ${SERVER_URL:http://localhost:18080}
  error:
    include-message: always

spring:
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      connect-timeout: 3s
      timeout: 5s
      lettuce:
        pool:
          time-between-eviction-runs: 300000

management:
  server:
    port: 18090
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "info, health, prometheus"
#        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoint:
    info:
      access: unrestricted
    health:
      access: unrestricted
    prometheus:
      access: read_only

logging:
  config: classpath:logback/logback-spring.xml
  loki:
    url: ${LOKI_URL}
#  pattern:
#    level: %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
#  include-application-name: false

redis:
  key-prefix: ${REDIS_KEY_PREFIX}
  connection-type: ${REDIS_CONNECTION_TYPE:standalone}

springdoc:
  swagger-ui:
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: -1
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

---
spring.config.activate.on-profile: local
spring:
  data:
    redis:
      host: ${REDIS_DEV_HOST}
      port: ${REDIS_DEV_PORT}
      password: ${REDIS_PASSWORD}

---
spring.config.activate.on-profile: dev
spring:
  data:
    redis:
      host: ${REDIS_DEV_HOST}
      port: ${REDIS_DEV_PORT}
      password: ${REDIS_PASSWORD}

---
spring.config.activate.on-profile: live
spring:
  data:
    redis:
      host: ${REDIS_DEV_HOST:127.0.0.1}
      port: ${REDIS_DEV_PORT:6379}
      cluster:
        max-redirects: 3
        nodes:
          - ${REDIS_CLUSTER_MASTER_NODE_1:}
          - ${REDIS_CLUSTER_MASTER_NODE_2:}
          - ${REDIS_CLUSTER_MASTER_NODE_3:}
          - ${REDIS_CLUSTER_WORKER_NODE_1:}
          - ${REDIS_CLUSTER_WORKER_NODE_2:}
          - ${REDIS_CLUSTER_WORKER_NODE_3:}
      password: ${REDIS_PASSWORD}
management:
  endpoints:
    web:
      base-path: ${GREENLIGHT_ACTUATOR_PATH}