spring.application.name: greenlight-prototype-core-api
spring.profiles.active: local

server:
  port: 18080
  error:
    include-message: always

management:
  server:
    port: 18090
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "info, health, prometheus"
#        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoint:
    info:
      access: unrestricted
    health:
      access: unrestricted
    prometheus:
      access: read_only

logging:
  config: classpath:logback/logback-spring.xml
  loki:
    url: http://43.202.94.66:43100/loki/api/v1/push
#  pattern:
#    level: %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
#  include-application-name: false
---
spring.config.activate.on-profile: local
spring:
  data:
    redis:
      host: ${STORAGE_REDIS_HOST}
      port: ${STORAGE_REDIS_PORT}
      password: ${STORAGE_REDIS_PASSWORD}
management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
    enabled: true
  zipkin:
    tracing:
      endpoint: http://43.202.94.66:49411/api/v2/spans


---
spring.config.activate.on-profile: dev
spring:
  data:
    redis:
      host: ${STORAGE_REDIS_HOST}
      port: ${STORAGE_REDIS_PORT}
      password: ${STORAGE_REDIS_PASSWORD}

---
spring.config.activate.on-profile: live
spring:
  data:
    redis:
      host: ${STORAGE_REDIS_HOST}
      port: ${STORAGE_REDIS_PORT}
      password: ${STORAGE_REDIS_PASSWORD}
management:
  endpoints:
    web:
      base-path: ${GREENLIGHT_ACTUATOR_PATH}
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
    enabled: true
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
